{
    'name': 'Quran Center Management',
    'version': '1.0',
    'summary': 'Manage Quran Memorization Centers, Students, Teachers, Payments, and Donations',
    'author': 'Ezzeldin Mohmed',
    'category': 'Education',
    'depends': ['base','mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/branch_views.xml',
        'views/teacher_views.xml',
        'views/student_views.xml',
        'views/payment_views.xml',
        'views/expense_views.xml',
        'views/donation_views.xml',
        'wizard/branch_report_wizard_view.xml',
        'wizard/student_payment_report_wizard_view.xml',
        'wizard/teacher_finance_report_wizard_view.xml',
        'views/menu_views.xml',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
